### ISSUE TITLE
"Error! Beta detected" on every image, API not connected?

### ISSUE THREAD

**Issue by TrustyRat** [silveredgold/beta-protection#74]
I set up Beta Protection with a local BetaCensor.Server, but after some hefty loading every image becomes "Error! Beta detected!". Local censoring also fails. Any idea what I might have gotten wrong?

The only error I can notice is the yellow X in the settings under API status.

**Comment by TrustyRat** [comment]
Forgot to include the log:

warn: ZiggyCreatures.Caching.Fusion.FusionCache[0]
      FUSION [N=CACHE_RESULTS] (O=0HMUJDRGJ0TFI K=//--the image's url--): an error occurred while calling the factory
      System.InvalidOperationException: This operation is not supported for a relative URI.
         at System.Uri.get_IsFile()
         at CensorCore.ImageSharpHandler.LoadImage(String path) in /home/runner/work/censor-core/censor-core/src/CensorCore/ImageSharpHandler.cs:line 48
         at CensorCore.AIService.RunModel[TTensor](String url, TensorLoadOptions`1 loadOptions, MatchOptions options) in /home/runner/work/censor-core/censor-core/src/CensorCore/AIService.cs:line 121
         at CensorCore.AIService.RunModel(String url, MatchOptions options) in /home/runner/work/censor-core/censor-core/src/CensorCore/AIService.cs:line 115
         at BetaCensor.Caching.CachedCensorImageRequestHandler.RunModel(CensorImageRequest request, MatchOptions options) in /home/runner/work/beta-censoring/beta-censoring/src/BetaCensor.Caching/CachedCensorImageRequestHandler.cs:line 1

**Comment by silveredgold** [comment]
Hmm, that's an odd one. As a potential workaround, does the error either change (or go away) if you turn off caching using the configuration file [as outlined here](https://silveredgold.github.io/beta-censoring/content/configuration.html#caching-configuration)?

Also, what version of Beta Censoring (the server) are you using?

**Comment by CypherBalance** [comment]
Also had this issue. Mostly solved it by closing the server window and reopening a few times.
